### ISSUE TITLE
shell files missing in 2nd_Place_ovfm

### ISSUE THREAD

**Issue by singhranjodh** [topcoderinc/Harvard-HMS-LC-MM1-Public#1]
I'm unable to find 'train.sh', 'test.sh' and 'config.sh' scripts mentioned in MarathonMatch-SolutionDescription-ovfm.docx  in 2nd_Place_ovfm directory.

**Comment by godenyb** [comment]
I updated ovfm's solution with his latest sources that contain compile and test scripts.
